### ISSUE TITLE
Need Resource Owner Password Flow

### ISSUE THREAD

**Issue by dongmei-cao** [okta/okta-auth-java#42]
I could be missing something. In the current Okta Java Authentication SDK (okta-auth-java), I don't see any implementation to support Resource Owner Password Flow (https://developer.okta.com/authentication-guide/implementing-authentication/password/#_2-using-the-resource-owner-password-flow). We need this flow in our product. Please support it. Thanks.

**Comment by nbarbettini** [comment]
@dongmei-cao This library is a client for the Okta [Authentication API](https://developer.okta.com/docs/api/resources/authn/), which is similar to the Resource Owner Password Flow but operates at a lower level (not OpenID Connect). This library isn't intended to work as an OIDC client.

We have a [Spring Boot integration](https://github.com/okta/okta-spring-boot) that does OIDC, but not the Resource Owner Password flow because it is not recommended for typical applications.

What's the scenario you need to support?

**Comment by dongmei-cao** [comment]
We have a public REST API allowing end users to download files from us. The REST API requires an OAuth access_token. The OAuth access_token is generated using the Resource Owner Password Flow. I'm Ok with Spring Boot integration if you can make it available over there. In fact, I'm using the Spring Boot Starter for the Management API. Thanks!
